{{- if .Values.app.isAccessible }}
{{- if or .Values.app.ingress.http .Values.app.ingress.http}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Values.app.name }}-ingressroute
    {{- if .Values.ingressController.clusterIssuer }}
        cert-manager.io/cluster-issuer: {{ .Values.ingressController.clusterIssuer }}
    {{- end }}
  labels:
    theketch.io/app-name: {{ $.Values.app.name }}
spec:
  entryPoints:
  {{- if  .Values.app.ingress.http }}
    - web
  {{- end }}
  {{- if  .Values.app.ingress.https }}
    - websecure
  {{- end }}
  routes:
{{- if  .Values.app.ingress.http }}
  {{- range $_, $cname := .Values.app.ingress.http }}
  - match: Host(`{{ $cname }}`)
    kind: Rule
    services:
    {{- range $_, $deployment := $.Values.app.deployments }}
    {{- range $_, $process := $deployment.processes }}
     {{- if $process.routable }}
    - name: {{ printf "%s-%s-%v" $.Values.app.name $process.name $deployment.version }}
      port: {{ $process.publicServicePort }}
      weight: {{$deployment.routingSettings.weight}}
      {{- end }}   
      {{- end }}   
      {{- end }}   
      {{- end }}   
  {{- end }}   
{{- if  .Values.app.ingress.http }}
  {{- range $_, $cname := .Values.app.ingress.https }}
  - match: Host(`{{ $cname }}`)
    kind: Rule
    services:
    {{- range $_, $deployment := $.Values.app.deployments }}
    {{- range $_, $process := $deployment.processes }}
     {{- if $process.routable }}
    - name: {{ printf "%s-%s-%v" $.Values.app.name $process.name $deployment.version }}
      port: {{ $process.publicServicePort }}
      weight: {{$deployment.routingSettings.weight}}
      {{- end }}   
      {{- end }}   
      {{- end }}   
      {{- end }}   
  {{- end }}   
{{- end }}
{{- end }}